server:
  port: 8082
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      password: root
      username: root
      initial-size: 5
      min-idle: 1
      max-active: 50
      max-wait: 50000

mybatis:
  check-config-location: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.yun.beat.bean

fastdfs:
  #fastdfs文件服务器地址
  tracker_servers: 192.168.2.200:22122
  charset: UTF-8


fdfs:
  connect-timeout: 601
  so-timeout: 1501
  tracker-list: 192.168.2.200:22122





